### ISSUE TITLE
Resaving `egovlp.pth` to only contain `state_dict`

### ISSUE THREAD

**Issue by gzhihongwei** [showlab/EgoVLP#11]
Can the pretrained model (i.e. `egovlp.pth`) be saved with just `state_dict`? I reimplemented this model, but was having a hard time loading the checkpoint in my implementation due to `config` I believe. Besides, I don't believe that those are needed at inference time either. Thanks!

**Comment by QinghongLin** [comment]
Hi @gzhihongwei , thanks for your interest, I have put this issue in TDL. I will update when I am done.

**Comment by shhuangcoder** [comment]
Hello, has this problem been solved?

**Comment by gzhihongwei** [comment]
@shhuangcoder The workaround that I found was to import `parse_config.py`, load the checkpoint, then resave another checkpoint with just `state_dict`
