### ISSUE TITLE
About EgoClip Dataset

### ISSUE THREAD

**Issue by cyfedu1024** [showlab/EgoVLP#12]
Hi, No doubt that's great job! I have a question for the EgoClip dataset, May i only clik the link of Ego4D to obtain meta dataset? Since i find the link that is corresponding to the EgoClip dataset  is egoclip.csv, that's not meta dataset. Thanks a lot!

**Comment by QinghongLin** [comment]
Hi, Thanks for your interest. 
EgoClip is the curation of the original Ego4d dataset.
If you want to find the original Ego4D metadata, please follow the guideline [here](https://ego4d-data.org/docs/start-here/) to download the narration annotations and metadata for each video.

**Comment by cyfedu1024** [comment]
Thanks a lot for your reply!
