### ISSUE TITLE
Yes, I only using the rgb features, without adopt other modality e.g., audio.

### ISSUE THREAD

**Issue by haoshuai714** [showlab/EgoVLP#16]
Yes, I only using the rgb features, without adopt other modality e.g., audio.

_Originally posted by @QinghongLin in https://github.com/showlab/EgoVLP/issues/15#issuecomment-1426811060_

**Comment by haoshuai714** [comment]
Could you give me a download link about EPIC dataset, which only contain rgb feature?  I found the EPIC dataset website provides a full EPIC dataset download link, which is too big and not to download. Thanks!

**Comment by QinghongLin** [comment]
Hi haoshuai, 
Sorry, due to the copyright, I cannot release the original datasets.

I download the EPIC dataset from this link:   https://academictorrents.com/details/d08f4591d1865bbe3436d1eb25ed55aae8b8f043
and I have tried several Torrents tools and finally download this dataset.
