### ISSUE TITLE
Video Compression is Very Slow

### ISSUE THREAD

**Issue by ShramanPramanick** [showlab/EgoVLP#2]
Hi,
I am trying to use the proposed EgoCLIP dataset, and following your video compression code. The 1st step is resizing the frames. 
`Resize the source videos with a short size equal to 256 by script ./utils/video_resize.py.`
I have found this step to be extremely slow with an ETA of 10 days. Have you also spent similar time on this, or do you have a faster way for resizing and computing the chunks?

**Comment by QinghongLin** [comment]
Hi, I suggest you use `multiprocessing` for compression and chunking.
I use multiple machines at the same time, and enable multi-processing on each machine. About 3 days.
I provide an example of how `multiprocessing` works below.


```python
import os
import time
import sys
import subprocess
from multiprocessing import Pool, Value

folder_path = '/ego4d/data'
output_path = '/ego4d_256/data'

def videos_resize(videoinfos):
    global count

    videoid, videoname = videoinfos

    if os.path.exists(os.path.join(output_path, videoname)):
        print(f'{videoname} is resized.')
        return

    inname = folder_path + '/' + videoname
    outname = output_path + '/' + videoname

    cmd = "ffmpeg -y -i {} -filter:v scale=\"trunc(oh*a/2)*2:256\" -c:a copy {}".format( inname, outname)
    subprocess.call(cmd, shell=True)

    return

if __name__ == "__main__":
    file_list = []
    mp4_list = [item for item in os.listdir(folder_path) if item.endswith('.mp4')]
    for id, video in enumerate(mp4_list):
        file_list.append([id, video])

    pool = Pool(4)
    pool.map(videos_resize, tuple(file_list))

    # for file in file_list:
    #    videos_resize(file)
```

**Comment by ShramanPramanick** [comment]
Thanks, this works!
