### ISSUE TITLE
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 3 

### ISSUE THREAD

**Issue by schowdhury671** [showlab/EgoVLP#21]
I am encountering the following issue while running the pretraining code

```
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 3 (pid: 407727) of binary: /fs/nexus-scratch/sanjoyc/anaconda/envs/egovlp/bin/python


raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

```

I am trying the run the code on a single A5000 Node with 4 GPUS

Any help is appreciated.

**Comment by QinghongLin** [comment]
Hello! It looks like there is some problem In distributed mode, you should first test whether the single-node multi-GPUs can communicate smoothly before running this codebase.
Please refer this tutorial for details https://pytorch.org/tutorials/intermediate/ddp_tutorial.html
Thanks!
