### ISSUE TITLE
On the setting of `num_frames`

### ISSUE THREAD

**Issue by Lyman-Smoker** [showlab/EgoVLP#25]
Thanks for your great work!

I am curious about the setting of `num_frames` of the pretrained model [EgoVLP_PT_BEST](https://drive.google.com/file/d/1-cP3Gcg0NGDcMZalgJ_615BQdbFIbcj7/view?usp=sharing). 

I noticed that, in one of the closed issues, you clarified that `num_frames=4` is used to train [EgoVLP_PT_BEST](https://drive.google.com/file/d/1-cP3Gcg0NGDcMZalgJ_615BQdbFIbcj7/view?usp=sharing). However, in `configs/pt/egoclip.json`, `num_frames=16` is used. 

Also, when loading [EgoVLP_PT_BEST](https://drive.google.com/file/d/1-cP3Gcg0NGDcMZalgJ_615BQdbFIbcj7/view?usp=sharing) using a config file with `num_frames=4`, I get an error of size mismatch (shown in the attached image). It seems that the `num_frames` is 16 in [EgoVLP_PT_BEST](https://drive.google.com/file/d/1-cP3Gcg0NGDcMZalgJ_615BQdbFIbcj7/view?usp=sharing).

Could you please further explain how the `num_frames` is defined across the different configs and  checkpoints?

Thanks for your help in advance! 

![image](https://github.com/showlab/EgoVLP/assets/56393778/d8989bcc-a39a-4585-aa36-e01f7c429f61)

**Comment by Haawron** [comment]
seems #4 is related to this
