### ISSUE TITLE
Any zero-shot/few-shot action recognition data on EPIC-Kitchens? 

### ISSUE THREAD

**Issue by vineetparikh** [showlab/EgoVLP#8]
Hi there, thanks so much for open-sourcing this! This looks super cool!

Is there any zero-shot/few-shot action recognition baseline for EPIC-Kitchens using EgoVLP? It looks like this model has downstream baselines for action recognition (including zero-shot/few-shot) on Charades, and for multi-instance retrieval for EPIC-Kitchens, but are there baselines on zero-shot/few-shot on EPIC-Kitchens? If not, what checkpoint would you recommend I start from to train a zero-shot or few-shot baseline for action recognition?

Thanks again for your help,
Vineet

**Comment by QinghongLin** [comment]
hi @vineetparikh ,
We have not performed the action recognition experiments on EPIC yet, if you want to conduct experiments, I recommend you use the checkpoint [EgoVLP_PT_BEST](https://drive.google.com/file/d/1-cP3Gcg0NGDcMZalgJ_615BQdbFIbcj7/view?usp=sharing) for zero-shot or fine-tuning, and you can regarding the class label as text, the way like Charades-Ego.

If you have tried it, can you have an update for me, we are looking forward this!
