### ISSUE TITLE
checkpoint of Charades-Ego EgoVLP Zero-shot model does not exist.

### ISSUE THREAD

**Issue by sega-hsj** [showlab/EgoVLP#9]
https://drive.google.com/file/d/108BR5TmIA-sfX3cXOW_wxtJtc4XhglO6/view?usp=sharing

**Comment by QinghongLin** [comment]
Hi, the checkpoint you mentioned should be the red arrow one. Please check the link again: https://drive.google.com/file/d/10lRA4Fldt-c5Azh5D2Zvjwi-_YR5ve5e/view.


<img width="822" alt="image" src="https://user-images.githubusercontent.com/103281027/208673948-5134e575-3074-4e2d-bfd0-530c5c32b22f.png">
